language: emacs-lisp
env:
  matrix:
    - emacs=emacs22
    - emacs=emacs23
    - emacs=emacs24
    - emacs=emacs-snapshot
  global:
    - SOME_TOKEN=some_value
matrix:
  allow_failures:
    - env: emacs=emacs23
    - env: emacs=emacs23
    - env: emacs=emacs-snapshot
install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -qq
  - sudo apt-get install -qq $emacs
script:
  $emacs -Q --batch --eval "(progn (add-to-list 'load-path \"./\") (require 'nix-package))"
