language: emacs-lisp
sudo: true
env:
  matrix:
    - emacs=emacs22
    - emacs=emacs23
    - emacs=emacs24
    - emacs=emacs-snapshot
matrix:
  allow_failures:
    - env: emacs=emacs22
    - env: emacs=emacs23
    - env: emacs=emacs-snapshot
install:
  - curl https://nixos.org/nix/install | sh
  - nix-env -i $emacs
script:
  $emacs -Q --batch --eval \
    "(progn (add-to-list 'load-path \"./\")
            (require 'nix-package)
            (list-nix-packages))"
